### ISSUE TITLE
Nuget Release fails

### ISSUE THREAD

**Issue by JonasSchubert** [JonasSchubert/semantic-release-presets#13]
```bash
[12:35:59 PM] [semantic-release] › ℹ  Running semantic-release version 23.0.0
(node:26) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-presets/plugins/ms-teams"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-presets/plugins/nuget"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "semantic-release-replace-plugin"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "semantic-release-presets/plugins/nuget"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "publish" from "semantic-release-presets/plugins/nuget"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "success" from "semantic-release-presets/plugins/ms-teams"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[12:36:01 PM] [semantic-release] › ✔  Loaded plugin "fail" from "semantic-release-presets/plugins/ms-teams"
[12:36:03 PM] [semantic-release] › ✔  

[REDACTED]

[12:36:03 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[12:36:03 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[12:36:03 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[12:36:03 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[12:36:03 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  

[REDACTED]

[12:36:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[12:36:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[12:36:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[12:36:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[12:36:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[12:36:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-presets/plugins/ms-teams"
[12:36:06 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-presets/plugins/ms-teams"
[12:36:06 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "semantic-release-presets/plugins/nuget"
NuGet Command Line
6.9.1.3
[12:36:07 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "semantic-release-presets/plugins/nuget"
[12:36:07 PM] [semantic-release] › ℹ  Found git tag v1.7.2 associated with version 1.7.2 on branch main
[12:36:07 PM] [semantic-release] › ℹ  Found 15 commits since last release
[12:36:07 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(nuget): bump dependency versions
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(npm): bump husky and configure, remove obsolete file
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(release): 1.7.3

[REDACTED]

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(project): merge branch 'renovate/all-minor-patch' into 'main'

chore(deps): update all non-major dependencies

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update all non-major dependencies
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(project): merge branch 'renovate/all-minor-patch' into 'main'

chore(deps): update all non-major dependencies

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update all non-major dependencies
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(project): merge branch 'renovate/all-minor-patch' into 'main' [skip ci]

chore(deps): update all non-major dependencies

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update all non-major dependencies
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(project): merge branch 'renovate/all-minor-patch' into 'main' [skip ci]

chore(deps): update dependency dotnet-reportgenerator-globaltool to v5.2.1

[REDACTED]

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update dependency dotnet-reportgenerator-globaltool to v5.2.1
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(project): merge branch 'renovate/all-minor-patch' into 'main' [skip ci]

chore(deps): update all non-major dependencies

[REDACTED]

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update all non-major dependencies
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(project): merge branch 'renovate/all-minor-patch' into 'main' [skip ci]

chore(deps): update all non-major dependencies

[REDACTED]

[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update all non-major dependencies
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:36:07 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 15 commits complete: patch release
[12:36:07 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:36:07 PM] [semantic-release] › ℹ  The next release version is 1.7.3
[12:36:07 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:36:07 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:36:07 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"

[REDACTED]

[12:36:07 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[12:36:07 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "semantic-release-replace-plugin"
[12:36:07 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "semantic-release-replace-plugin"
[12:36:07 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"

[REDACTED]

[12:36:07 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[12:36:07 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[12:36:07 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[12:36:11 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v1.7.3
[12:36:11 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[12:36:11 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:36:11 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:36:11 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "semantic-release-presets/plugins/nuget"
[12:36:11 PM] [semantic-release] [semantic-release-presets/plugins/nuget] › ℹ  

[REDACTED]

Package source with Name: gitlab added successfully.
[12:36:11 PM] [semantic-release] [semantic-release-presets/plugins/nuget] › ℹ  Packing with configuration Release.
  Determining projects to restore...
  Restored /builds/[REDACTED].csproj (in 8.95 sec).
  Restored /builds/[REDACTED].csproj (in 8.95 sec).
/usr/share/dotnet/sdk/8.0.201/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(221,5): error NU5026: The file '/builds/[REDACTED].dll' to be packed was not found on disk. [/builds/[REDACTED].csproj]
[12:36:22 PM] [semantic-release] [semantic-release-presets/plugins/nuget] › ✘  Error: Command failed with exit code 1: dotnet pack --configuration Release --output output --nologo 
    at makeError (file:///usr/lib/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///usr/lib/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async default (file:///usr/lib/node_modules/semantic-release-presets/plugins/nuget/prepare.js:31:5)
    at async validator (file:///usr/lib/node_modules/semantic-release/lib/plugins/normalize.js:36:24)
    at async file:///usr/lib/node_modules/semantic-release/lib/plugins/pipeline.js:38:36
    at async file:///usr/lib/node_modules/semantic-release/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as prepare] (file:///usr/lib/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///usr/lib/node_modules/semantic-release/index.js:202:3)
    at async Module.default (file:///usr/lib/node_modules/semantic-release/index.js:278:22)
[12:36:22 PM] [semantic-release] › ✘  Failed step "prepare" of plugin "semantic-release-presets/plugins/nuget"
[12:36:22 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/gitlab"
[12:36:22 PM] [semantic-release] [@semantic-release/gitlab] ›

[REDACTED]

[12:36:22 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/gitlab"
[12:36:22 PM] [semantic-release] › ℹ  Start step "fail" of plugin "semantic-release-presets/plugins/ms-teams"
[12:36:24 PM] [semantic-release] [semantic-release-presets/plugins/ms-teams] › ℹ  Message sent to Microsoft Teams
[12:36:24 PM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-presets/plugins/ms-teams"
[12:36:24 PM] [semantic-release] › ✘  EDOTNET_PACK_FAILED dotnet pack failed with exit code 1
dotnet pack --configuration Release --output output --nologo

SemanticReleaseError: dotnet pack failed with exit code 1
    at default (file:///usr/lib/node_modules/[4msemantic-release-presets[24m/plugins/nuget/prepare.js:41:11)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async validator (file:///usr/lib/node_modules/[4msemantic-release[24m/lib/plugins/normalize.js:36:24)
    at async file:///usr/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:38:36
    at async file:///usr/lib/node_modules/[4msemantic-release[24m/lib/plugins/pipeline.js:32:5
    at async pluginsConfigAccumulator.<computed> [as prepare] (file:///usr/lib/node_modules/[4msemantic-release[24m/lib/plugins/index.js:87:11)
    at async run (file:///usr/lib/node_modules/[4msemantic-release[24m/index.js:202:3)
    at async Module.default (file:///usr/lib/node_modules/[4msemantic-release[24m/index.js:278:22)
    at async default (file:///usr/lib/node_modules/[4msemantic-release[24m/cli.js:55:5) {
  code: [32m'EDOTNET_PACK_FAILED'[39m,
  details: [32m'dotnet pack --configuration Release --output output --nologo'[39m,
  semanticRelease: [33mtrue[39m,
  pluginName: [32m'semantic-release-presets/plugins/nuget'[39m
}section_end:1708346195:step_script
```

**Comment by JonasSchubert** [comment]
False positive due to misconfiguration of project.
